
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_aws
    ports:
      - "5432:5432"
